LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;

ENTITY RU IS
PORT( CLK, CLR, ESCD, ESCI: IN STD_LOGIC;
	CNT: IN STD_LOGIC_VECTOR(1 DOWNTO 0);
	EP: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	Q: INOUT STD_LOGIC_VECTOR(7 DOWNTO 0)
	);
END ENTITY;

ARCHITECTURE A_RU OF RU IS
SIGNAL D: STD_LOGIC_VECTOR(7 DOWNTO 0);
BEGIN
	MUX: PROCESS (CNT, Q, ESCD, ESCI, EP)
	BEGIN
		CASE CNT IS
		WHEN "00" => D <= EP;
		WHEN "01" => CICLO1: FOR I IN 7 DOWNTO 1 LOOP
						D(I) <= Q(I-1);
					END LOOP CICLO1;
					D(0) <= ESCD;
		WHEN "10" => CICLO2: FOR I IN 0 TO 6 LOOP
						D(I) <= Q(I+1);
					END LOOP CICLO2;
					D(7) <= ESCI;
		WHEN OTHERS => D<= Q;
		END CASE;
   END PROCESS MUX;

   PROCESS (CLK, CLR)
   BEGIN
   		IF(CLR='0') THEN
 	    	Q <= "00000000";
		ELSIF (CLK'EVENT AND CLK='1') THEN
			Q <= D;
		END IF;
	END PROCESS;
END A_RU;
